UI For The Backup/Restore Managed Instance Feature
nemanja-milovancevic/azuredatastudio pull request #5
Opened 2022-04-12 10:21 UTC by nemanja-milovancevic

In the following pull request, you can find changes necessary to enable backup and restore features for the Managed Instance version of the SQL Server. Additionally, user can backup SQL Server Box databases to URL and restore them from URL. Feel free to comment if you want to disable this feature for the SQL Server Box.

Backup and restore don't work for Managed Instance in ADS. This problem exists because ADS didn't support backup to URL and restore from URL and partially because Managed Instance only supports a subset of backup and restore features. Managed Instance internally takes automatic backups, so the user can only make a copy-only backup. This type of backup is independent of other backups, and other backups are not dependent on copy-only backup.

If you want to backup to URL:

- Connect to the Managed Instance.
- Choose the Databases tab on the main dashboard.
- Choose a database from the list.
- Wait for the spinner to disappear. You'll see a dialog like this:
![image](https://user-images.githubusercontent.com/28262823/162934847-05a2b1ae-25ce-4c11-a12c-cc7462b5576b.png)
- Click on the Browse button. You'll see a URL browser dialog:
![image](https://user-images.githubusercontent.com/28262823/162935165-84165022-9544-494b-a9b8-1b04ced799f6.png)
- Choose an Azure account from the list. If there is no Azure account in the list, click on the Link account to link a new one.
- Choose tenant, subscription, storage account, and blob container.
- Click on the Create Credentials button.
- Optionally rename the backup file.
- Click the OK button. URL browser dialog will disappear.
- Click on the Backup button.

If you want to restore a backup from a URL, you can do it in a similar fashion. The only major difference is that you would need to choose a backup file from the blob. That's why the restore URL browser dialog looks different from the backup URL browser dialog.
![image](https://user-images.githubusercontent.com/28262823/162937783-486d93ca-e507-4721-8829-06c16bbed727.png)

2022-04-12 17:03 UTC, Charles-Gagnon requested changes

2022-04-12 17:03 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/browser/urlBrowserDialog.ts
> +	private setBlobContainersSelectorBoxErrors(errors: any) {
You don't seem to be using the parameter at all

2022-04-12 17:03 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/browser/urlBrowserDialog.ts
> +		this._backupFileSelectorBox.setOptions(['Error getting backup files']);
localize

2022-04-12 17:03 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/browser/urlBrowserDialogController.ts
> + * File browser dialog service
URL Browser dialog service

2022-04-12 17:03 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/browser/urlBrowserDialogController.ts
> +export class UrlBrowserDialogController implements IUrlBrowserDialogController {
`UrlBrowserDialogService` and `IUrlBrowserDialogService`

2022-04-12 17:03 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/common/urlBrowserDialogController.ts
> +	 * Show file browser dialog
URL browser

2022-04-13 15:38 UTC, Charles-Gagnon commented on .eslintrc.json
> +					"mssql",
All of these are duplicated - mssql is already in the lists for each of these sections.

2022-04-26 20:40 UTC, Charles-Gagnon requested changes

2022-04-26 20:40 UTC, Charles-Gagnon commented on .eslintrc.json
> +					"mssql",
Please put these back where they were - no reason for these to change in this PR

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/contrib/backup/browser/backup.component.ts
> +			if (this._engineEdition === DatabaseEngineEdition.SqlManagedInstance) {
Please add comment explaining why this is disabled for MI

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/contrib/backup/browser/backup.component.ts
> +			// Set backup path list
Remove this comment, it doesn't add any value

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/contrib/backup/browser/backup.component.ts
> +			this.copyOnlyCheckBox!.checked = true;
Why is this changing?

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/browser/urlBrowserDialog.ts
> +		let azureAccountLabel = localize('azurebrowser.account', "Azure Account*");
What's the * for? If this is a required field you should be setting the required property field, not adding it directly to the string

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/browser/urlBrowserDialog.ts
> +		this._sasButton.label = 'Create Credentials';
Localize

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/browser/urlBrowserDialog.ts
> +		let sharedAccessSignatureLabel = localize('azurebrowser.sharedAccessSignature', "Shared access signature generated*");
Is the * intentional?

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/browser/urlBrowserDialog.ts
> +		let backupFileLabel = localize('azurebrowser.backupFile', "Backup file*");
Another *

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/browser/urlBrowserDialog.ts
> +		this._accountSelectorBox.setOptions([reason]);
Does this handle error objects correctly?

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/browser/urlBrowserDialog.ts
> +	private setStorageAccountSelectorBoxError(errors: any) {
You don't appear to be using errors anywhere

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/browser/urlBrowserDialog.ts
> +	private setBackupFilesSelectorError(errors: any) {
Not using errors?

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/browser/urlBrowserDialog.ts
> +		this.show();
Is this really going to take long enough that it's worth having the spinner show?

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/browser/urlBrowserDialog.ts
> +			.then(getStorageAccountAccessKeyResult => {
Instead of using nested .thens it would be much more preferable to make this function async (and then the caller could choose to await it or not)

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/services/fileBrowser/browser/urlBrowserDialog.ts
> +		return nextYear.toLocaleString().split(',')[0];
Is calling toLocaleString what you want to do here? That's going to change based on the users locale - don't we want to control the format the date is in exactly?

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/services/restore/browser/restoreDialog.ts
> +			placeholder: localize('targetDatabaseTooltip', ""),
Purposely empty?

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/services/restore/browser/restoreDialog.ts
> +			this.viewModel.sourceDatabaseName = null;
undefined, not null

2022-04-26 20:40 UTC, Charles-Gagnon commented on src/sql/workbench/services/restore/browser/restoreDialog.ts
> +			selectedDatabase = null;
undefined, not null

2022-04-26 20:56 UTC, Charles-Gagnon commented
1. You have merge conflicts
2. Once you've addressed the issues here could you please open up the PR in the ADS repo so we can more easily get other eyes on it?

2022-04-27 12:35 UTC, nemanja-milovancevic commented on src/sql/workbench/services/restore/common/constants.ts
> +export enum DeviceType {
Hi Charles, these constants are already in the `src\sql\workbench\contrib\backup\common\constants.ts`. They represent backup [media device type](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.devicetype?view=sql-smo-160). There is a [physical device type](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.backupdevicetype?view=sql-smo-160) too. Both are used as backup RPC params. You can see that in `src\sql\workbench\contrib\backup\browser\backup.component.ts` in method `createBackupInfo`. The first one as the `backupDeviceType` and the second in the `backupPathDevices` map.

2022-04-27 16:34 UTC, Charles-Gagnon commented on src/sql/workbench/services/restore/common/constants.ts
> +export enum DeviceType {
Ok, but please still add the comments to the code so others looking at this know what these represent and ideally what they map to when creating the backup query statement

2022-04-29 09:23 UTC, closed without merging